### PR TITLE
adding new list

### PR DESCRIPTION
**Pull request by scafroglia93**

### CODE REVIEW

**Comment by scafroglia93** [comment]
1- Stamparm
The level of the list must be evaluated
Readme ->
https://github.com/stamparm/ipsum

**Comment by wbartels** [comment]
Thanks for the feedback.
I have no intention to add more blocklists at the moment.
Of course you are free to make your own changes to the blocklists.

**Comment by scafroglia93** [comment]
italiancert it's related to italian national state cert -> ENISA MEMBER

**Comment by scafroglia93** [comment]
I have some lists that instead of being updated are re-downloaded every time ->
[!] Redownload

Is there any way to avoid it?

**Pull request closed without merging**
